services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

